### ISSUE TITLE
Unable to run ngdoc in Yeoman application

### ISSUE THREAD

**Issue by michaelenger** [bevacqua/grunt-ngdoc#1]
Hey, I'm trying to generate docs for an angular app created using [Yeoman](http://yeoman.io/) and using the basic example results in 0 pages being generated.

Here is my `ngdoc` config:

``` javascript
    ngdoc: {
        all: ['<%= yeoman.app %>/scripts/**/*.js']
    }
```

I'm running Grunt v0.4.5 on Node v0.10.26 and I am able to generate documents using the same path with `jsdoc` so I'm wondering if I'm missing some ngdoc comment which will make it parse my files.

**Comment by petukhov** [comment]
I have the same issue.
