### ISSUE TITLE
error with duplicate 

### ISSUE THREAD

**Issue by idefy** [bevacqua/grunt-ngdoc#4]
There is an error when displaying the documentation that was really hard to track down.
The problem would happen if in the documentation has two directives, for instance, with the same @name

I get this error:
[ngRepeat:dupes] http://errors.angularjs.org/1.2.16/ngRepeat/dupes?p0=page%20in%20pages%20track%20by%20page.url&p1=general%2Floading

I understand that, for good practices, names should be unique. But it would be good if doc generation  could warn of such duplicate names, otherwise it makes it hard to track and solve.

Otherwise good job with the tool so far.
I wish the documentation would add the entire path, that is the module:theNgDocType

**Comment by bevacqua** [comment]
You're welcome to create a pull request for this feature. I'm not really using the module anymore but I'll maintain it and bump the package version
